### ISSUE TITLE
What is required to be able to handle streams in _dbop()?

### ISSUE THREAD

**Issue by jesseclark** [apb2006/basex-node#13]
Hello, 

First off thanks for creating these node bindings for BaseX. I think it is going to be a big help on my current project.

I'm building a web api that receives xml files in a post request and adds them to my BaseX db. Currently I am writing the received file to disk then opening it and passing it as string data to the Session.add() method.

It would be nice if I could stream the data directly to add() without having to hit the disk. I have access to the incoming readStream but it looks like stream support has not been added in _dbop(). 

Did you have a solution for this in mind? If you could give me an overview perhaps I could help implement it.

It looks like the action hinges around line 320 of index.js in sendQueueItem():

``` javascript
self.send(cmd.send);
```

and in this.send() line 144:

``` javascript
if (typeof s === "function")
            s = s();
```

so it seems like we would need to modify _dbop() to check if the input is a string or a stream and if it is a stream, instead of passing the command as a string like so (line 219 this._dbop()):

``` javascript
send : op + path + "\0" + input+"\0",
```

add a reference to the stream and other command components to the command object and make send a reference to a function that will read the stream:

``` javascript
send : this.readStream,
op: op,
path: path,
input: input 
```

and then this.readStream() could read the input stream and then return the assembled command in the format: 

``` javascript
return op + path + "\0" + streamData + "\0";
```

I'm still a relative beginner with node so I might be a bit off on my proposed solution and would appreciate any feedback or let me know what you were thinking for a solution.

Best,
-Jesse

**Comment by apb2006** [comment]
merged some time ago
