### ISSUE TITLE
Next query executed after failed query returns invalid output

### ISSUE THREAD

**Issue by jacobborisov** [apb2006/basex-node#21]
Hello. I have following script to perform a test:

```
const basex = require('basex')
var session = new basex.Session()

function performQuery(q_str) {
    return new Promise(rs => {
        var q = session.query(q_str)
        q.execute((e, r) => {
            console.log("Result: ", r.result, "; Error:", e)
            rs()
        })
    })
}

var invalid_query = '(map {"key": "value"})("missing")("key")'
var correct_query = '(map {"key": "value"})("key")'
```

If I try to perform two correct queries in turn:
```
performQuery(correct_query).then(
    performQuery(correct_query)
)
```
all seem to be work as expected:
```
Result:  value ; Error: null
Result:  value ; Error: null
```
But if I put invalid query at first:
```
performQuery(invalid_query).then(
    performQuery(correct_query)
)
```
result of the next query also incorrect:
```
Result:  undefined ; Error:
Result:   ; Error: null
```

Is it a bug in your library or I simply doing something wrong? Thanks.

**Comment by apb2006** [comment]
Hi Jacob,
Looks like a bug in my library (in the parsing of the error response ) to me. 
I will take a look and try to fix it in the next day or so. This project has been a bit neglected (last used with Node 0.6)
Meantime you could try https://github.com/alxarch/basex-stream which appears to handle the comms in the cleaner fashion.
/Andy

**Comment by apb2006** [comment]
`query.results` was handling errors ok but `query.execute` was not pulling error message from stream. Will package and push to npm this week.

**Comment by apb2006** [comment]
v0.8.0 now released to npm should fix this issue. Thanks for reporting.

**Comment by jacobborisov** [comment]
I can confirm that the problem has been fixed in my case. Thanks for the quick resolution!

**Comment by apb2006** [comment]
thanks
