### ISSUE TITLE
basex.Session

### ISSUE THREAD

**Issue by tcdaly** [apb2006/basex-node#24]
Hello,
In
`var session=basex.Session(host, port, username, password)`
is basex.Session a synchronous function?  Can it be assumed that the session was created successfully if no socketError event is emitted?
Thanks.

**Comment by apb2006** [comment]
The `Session` function only starts the connection process by calling  [net.createConnection](https://nodejs.org/api/net.html#net_net_createconnection_port_host_connectlistener). The rest is asynchronous. Each `Session` has a state
```
var states = {
    DISCONNECTED: 0,
    CONNECTING: 1,
    AUTHORIZE: 2,
    CONNECTED: 3,
    CLOSING: 4
};
```
Immediately after a session object is created with no error it is in state CONNECTING

**Comment by tcdaly** [comment]
Thank you.  Is there a way then that my application can be informed when the connection has been made successfully?

**Comment by apb2006** [comment]
The session will emit a "connect" event https://github.com/apb2006/basex-node/blob/master/index.js#L127
