### ISSUE TITLE
basex-node does not handle server disconnection gracefully

### ISSUE THREAD

**Issue by hanshuebner** [apb2006/basex-node#9]
Hi,

when leaving my node process connected to BaseX running over night, it crashed when it lost connection to the database server.  It seems that there is currently no way to prevent this, as node-basex does not handle the possible closing of the socket by the database server, and tries to interact with a closed socket, which results in an uncaught exception.

It would be useful if an event would be generated when a Session lost its connection (by making it an EventEmitter and forwarding the 'end' event).  Furthermore, session.close() should detect when the socket is already closed and not try to read or write from it in that case.

This would allow application code to set up an event handler that logged the event and performed an automatic reconnection, if desired.

I can come up with a patch if you don't have the time to look into implementing this yourself.  Please let me know.

Thanks!
Hans

**Comment by apb2006** [comment]
See `examples/issue11.js` for one approach
